Joneco\Shopify\Model\Common\PriceSet:
    properties:
        shopMoney:
            type: Joneco\Shopify\Model\Common\Price
        presentmentMoney:
            type: Joneco\Shopify\Model\Common\Price