Joneco\Shopify\Model\Orders\Common\RefundLineItem:
    properties:
        id:
            type: int
        quantity:
            type: int
        lineItemId:
            type: int
        locationId:
            type: int
        restockType:
            type: string
        subtotal:
            type: float
        totalTax:
            type: float
        subtotalSet:
            type: Joneco\Shopify\Model\Common\PriceSet
        totalTaxSet:
            type: Joneco\Shopify\Model\Common\PriceSet
        lineItem:
            type: Joneco\Shopify\Model\Orders\Common\LineItem