Joneco\Shopify\Model\Orders\Common\DiscountAllocation:
    properties:
        amount:
            type: string
        discountApplicationIndex:
            type: int
        amountSet:
            type: Joneco\Shopify\Model\Common\PriceSet