Joneco\Shopify\Model\Orders\Common\ShippingLine:
    properties:
        code:
            type: string
        price:
            type: string
        priceSet:
            type: Joneco\Shopify\Model\Common\PriceSet
        discountedPrice:
            type: string
        discountedPriceSet:
            type: Joneco\Shopify\Model\Common\PriceSet
        source:
            type: string
        title:
            type: string
        taxLines:
            type: array<Joneco\Shopify\Model\Orders\Common\TaxLine>
        carrierIdentifier:
            type: string
        requestedFulfillmentServiceId:
            type: string