Joneco\Shopify\Model\Orders\Common\LineItemDuty:
    properties:
        shopMoney:
            type: Joneco\Shopify\Model\Common\Price
        presentmentMoney:
            type: Joneco\Shopify\Model\Common\Price
        id:
            type: int
        harmonizedSystemCode:
            type: string
        taxLines:
            type: array<Joneco\Shopify\Model\Orders\Common\TaxLine>
        adminGraphqlApiId:
            type: string