Joneco\Shopify\Model\Orders\Common\TaxLine:
    properties:
        title:
            type: string
        price:
            type: string
        rate:
            type: float
        priceSet:
            type: Joneco\Shopify\Model\Common\PriceSet