Joneco\Shopify\Model\Shipping\FulfillmentOrder:
    properties:
        id:
            type: int
        shopId:
            type: int
        orderId:
            type: int
        assignedLocationId:
            type: int
        fulfillmentServiceHandle:
            type: string
        requestStatus:
            type: string
        status:
            type: string
        supportedActions:
            type: array<string>
        destination:
            type: Joneco\Shopify\Model\Shipping\Common\Destination
        lineItems:
            type: array<Joneco\Shopify\Model\Shipping\Common\LineItem>
        assignedLocation:
            type: Joneco\Shopify\Model\Inventory\Location
        merchantRequests:
            type: array<Joneco\Shopify\Model\Shipping\Common\MerchantRequest>