Joneco\Shopify\Model\Store\ShippingZone:
    properties:
        name:
            type: string
        countries:
            type: array<Joneco\Shopify\Model\Store\Country>
        provinces:
            type: array<Joneco\Shopify\Model\Store\Province>
        carrierShippingRateProviders:
            type: array<Joneco\Shopify\Model\Store\Common\CarrierShippingRateProvider>
        priceBasedShippingRates:
            type: Joneco\Shopify\Model\Store\Common\PriceBasedShippingRate
        weightBasedShippingRates:
            type: Joneco\Shopify\Model\Store\Common\WeightBasedShippingRate